FILES = smlnj-lib/Util/utf8-sig.sml \
	smlnj-lib/Util/utf8.sml \
	ml-lpt/lib/stream-pos.sml \
	ml-lpt/lib/antlr-lexer-sig.sml \
	ml-lpt/lib/antlr-tokens-sig.sml \
	ml-lpt/lib/ebnf.sml \
	ml-lpt/lib/repair.sml \
	ml-lpt/lib/ulex-buffer.sml \
	ml-lpt/lib/wrapped-strm.sml \
	cmlib/hash-inc.sig \
	cmlib/hash-inc.sml \
	cmlib/idict.sig \
	cmlib/hashable.sig \
	cmlib/hash-table.sig \
	cmlib/hash-table.sml \
	parse.sml \
	scan.ulex.sml \
	resource.sml \
	proglr.sml

RESOURCES = cmlib/hash-table.smi \
            cmlib/idict.sig \
            cmlib/hash-inc.smi \
            cmlib/hashable.sig \
            cmlib/LICENSE \
            cmlib/hash-table.sml \
            cmlib/hash-table.sig \
            cmlib/hash-inc.sig \
            cmlib/AUTHORS \
            cmlib/hash-inc.sml \
            smlnj-lib/PORTING \
            smlnj-lib/Util/utf8-sig.sml \
            smlnj-lib/Util/utf8.mlb \
            smlnj-lib/Util/utf8.sml \
            smlnj-lib/Util/utf8-sig.smi \
            smlnj-lib/Util/utf8.smi \
            smlnj-lib/Util/README \
            smlnj-lib/Util/TODO \
            smlnj-lib/LICENSE \
            smlnj-lib/README \
            smlnj-lib/CHANGES \
            smlnj-lib/TODO \
            ml-lpt/lib/stream-pos.sml \
            ml-lpt/lib/antlr-tokens-sig.smi \
            ml-lpt/lib/ebnf.smi \
            ml-lpt/lib/err-handler.sml \
            ml-lpt/lib/wrapped-strm.sml \
            ml-lpt/lib/err-handler.smi \
            ml-lpt/lib/wrapped-strm.smi \
            ml-lpt/lib/ulex-buffer.sml \
            ml-lpt/lib/repair.smi \
            ml-lpt/lib/ulex-buffer.smi \
            ml-lpt/lib/antlr-lexer-sig.smi \
            ml-lpt/lib/antlr-tokens-sig.sml \
            ml-lpt/lib/stream-pos.smi \
            ml-lpt/lib/mllpt-lib.mlb \
            ml-lpt/lib/antlr-lexer-sig.sml \
            ml-lpt/lib/ebnf.sml \
            ml-lpt/lib/repair.sml \
            ml-lpt/lib/ml-lpt-lib.cm \
            ml-lpt/lib/ml-lpt-lib.mlb \
            ml-lpt/lib/ml-lpt-lib.smi

proglr: parse.sml scan.ulex.sml resource.sml proglr.sml boot.sml
	./polybuild.tcl $(FILES)
	polyc -o proglr a.o

debug: parse.sml scan.ulex.sml resource.sml proglr.sml boot.sml
	env DEBUG=1 ./polybuild.tcl $(FILES)

scan.ulex.sml: scan.ulex
	ml-ulex scan.ulex

mkresource: mkresource.sml
	polyc -o mkresource mkresource.sml

resource.sml: mkresource
	./mkresource Resource $(RESOURCES) >  resource.sml

clean:
	rm -f proglr
	rm -f mkresource
	rm -f *.o
