MKRESOURCE = ./mkresource

proglr: parse.sml scan.ulex.sml resource.sml proglr.sml boot.sml 
	mlton \
	-output 'proglr' \
	proglr.mlb 

scan.ulex.sml: scan.ulex
	ml-ulex scan.ulex

check: proglr
	runtest --tool mlton

$(MKRESOURCE): mkresource.sml mkresource-boot.sml
	mlton -output $(MKRESOURCE) mkresource.mlb

include Makefile.mkresource

clean:
	rm -f proglr
	rm -f mkresource
